version '2'
services
  redis1
    image redis
    ports
      - "6379:6379"

  db
    image postgres
    environment
      - POSTGRES_PASSWORD=adminadmin
      - DB_HOST=host.docker.internal
      - POSTGRES_USER=admin
      - PGDATA=varlibpostgresqldatapgdata
    ports
      - "5432:5432"
    volumes
      - datadbvarlibpostgresqldatapgdata

  rabbit
    image rabbitmq3-management
    environment
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin2017
    ports
      - "5672:5672"

volumes
 datadb  
    external true
    name datadb