version: '3.9'
services:
    redis:
      image: redis:latest
      ports:
      - "6379:6379"
    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - "MYSQL_ROOT_PASSWORD=123"
      volumes:
        - mariadb:/var/lib/mysql
      ports:
        - "3306:3306"
    # es:
    #   image: elasticsearch:7.6.0
    #   environment:
    #     - "discovery.type=single-node"
    #   ports:
    #     - "9200:9200"
    #     - "9300:9300"
    app:
      build: .
      command: bash -c ' ./railss.sh'
      environment:
        - "REDIS_URL=redis://redis/1"
        - "REDIS_HOST=redis"
      volumes:
        - .:/app
      ports:
        - "3000:3000"

      depends_on:
        - db
        - redis
        # - es

    sidekiq :
      build: .
      command: bundle exec sidekiq
      environment:
        - "REDIS_URL=redis://redis/1"
        - "REDIS_HOST=redis"
      volumes:
        - .:/app
      depends_on:
        - db
        - redis
        

volumes:
  mariadb:
    external: true
    name: mariadb
