version: '3.9'
services:
    redis:
      image: redis:latest
      ports:
      - "6379:6379"
    db:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=123
      volumes:
        - db-data:/var/lib/mysql
      ports:
        - "3306:3306"
    es:
      image: elasticsearch:7.6.0
      ports:
        - "9200:9200"
    sidekiq:
      build: .
      command: bundle exec sidekiq
      depends_on:
        - redis
      volumes:
        - .:/app
    web:
      build: .
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      depends_on:
        - db
        - sidekiq
volumes:
  db-data:
